vich_uploader:
    db_driver: orm
    mappings:
        user_img:
            uri_prefix:         /uploads/user-img
            upload_destination: '%kernel.root_dir%/../public/uploads/user-img'
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        company_img:
            uri_prefix:         /uploads/company-img
            upload_destination: '%kernel.root_dir%/../public/uploads/company-img'
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        parameter_img:
            uri_prefix:         /uploads/parameter-img
            upload_destination: '%kernel.root_dir%/../public/uploads/parameter-img'
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
